language: c

jobs:
 allow_failures:
  - os: windows

 include:
  - os: linux
    dist: precise
    compiler: gcc
    before_script:
     - cd gancc/src
    script: make
  - os: linux
    dist: precise
    compiler: clang
    before_script:
     - cd gancc/src
    script: make

  - os: linux
    dist: trusty
    compiler: gcc
    before_script:
     - cd gancc/src
    script: make
  - os: linux
    dist: trusty
    compiler: clang
    before_script:
     - cd gancc/src
    script: make

  - os: linux
    dist: bionic
    compiler: gcc
    before_script:
     - cd gancc/src
    script: make
  - os: linux
    dist: bionic
    compiler: clang
    before_script:
     - cd gancc/src
    script: make

  - os: linux
    dist: xenial
    compiler: gcc
    before_script:
     - cd gancc/src
    script: make
  - os: linux
    dist: xenial
    compiler: clang
    before_script:
     - cd gancc/src
    script: make

  - os: osx
    osx_image: xcode9
    compiler: clang
    before_script:
     - cd gancc/src
    script: make

  - os: windows
    compiler: gcc
    before_script:
     - cd gancc/src
    script: nmake
  - os: windows
    compiler: clang
    before_script:
     - cd gancc/src
    script: nmake

